workflows:
  racing-game-android:
    name: Racing Game Android
    max_build_duration: 60

    environment:
      java: 17

      android_signing:
        - racing_release

    scripts:
      - name: Make Gradle executable
        script: |
          chmod +x gradlew

      - name: Clean project
        script: |
          ./gradlew clean

      - name: Build Release APK
        script: |
          ./gradlew assembleRelease

      - name: Build Release AAB
        script: |
          ./gradlew bundleRelease

    artifacts:
      - app/build/outputs/apk/release/*.apk
      - app/build/outputs/bundle/release/*.aab

    publishing:
      email:
        recipients:
          - YOUR_EMAIL@example.com
        notify:
          success: true
          failure: true
